### ISSUE TITLE
Failed to refresh access token, token in response is null

### ISSUE THREAD

**Issue by peterbullmatti** [coskuncay/flutter_chatgpt_api#2]
Hi, thanks for the package!
I did as tutorial told, but got this error:
Exception: ChatGPT failed to refresh auth token: Exception: Failed to refresh access token, token in response is null

could you please let me know which part is wrong? I copied my token and created two dart file in lib and test. Thanks again!

**Comment by coskuncay** [comment]
Are you sure you copied the correct token and created files with correct names?

**Comment by peterbullmatti** [comment]
hi coskuncay, thanks for reply, its my mistake;)

**Comment by coskuncay** [comment]
@peterbullmatti  so glad you solved it 🙌
