### ISSUE TITLE
I cannot found session_token.dart file in your example

### ISSUE THREAD

**Issue by jishaofeng89** [coskuncay/flutter_chatgpt_api#8]
![image](https://user-images.githubusercontent.com/4972984/211123145-a9b3f838-5c4e-46c0-bd7c-69bc44a7231c.png)

![image](https://user-images.githubusercontent.com/4972984/211123187-d5b7bc2e-30c4-4e6c-bbaf-99b9abda90ad.png)

**Comment by wxkly8888** [comment]
So do I, any suggestion

**Comment by coskuncay** [comment]
Hİ @jishaofeng89 , @wxkly8888 
you need to add files to
example/lib/session_token.dart
example/lib/clearance_token.dart
test/session_token.dart
test/clearance_token.dart

like this

<img width="846" alt="image" src="https://user-images.githubusercontent.com/29631083/211796064-baed4f21-ae97-4631-b3db-0b1c1a0bf911.png">
